### ISSUE TITLE
Handler setup query

### ISSUE THREAD

**Issue by MRC-CBT** [Kaliumhexacyanoferrat/GenHTTP#105]
Hi there,

I have been trying to use GenHTTP to intercept some http api calls as a form of integration test. I have managed to create my test framework but have hit a problem where the API takes requests in the form http://someweb.com/api/method/id where id is any string but my handler expects http://someweb.com/api/method?id=a12345. How can I set a handler to take one or more parts of the path and use them as parameters please?
Many thanks for your time,
Matt

**Comment by Kaliumhexacyanoferrat** [comment]
Hi Matt,

I guess you are using the `Webservice` module? You can use variables there to define path variables (see [the docs](https://genhttp.org/documentation/content/webservices)):

```csharp
class Program
{

    static int Main(string[] args)
    {
        var api = Layout.Create()
                        .AddService<Service>("api");

        return Host.Create()
                   .Handler(api)
                   .Run();
    }

}

public class Service
{

    [ResourceMethod("method")]
    public string MethodByQuery(string id) => id;

    [ResourceMethod("method/:id")]
    public string MethodByPath(string id) => id;


}
```

This example allows you to access http://localhost:8080/api/method?id=a12345 as well as http://localhost:8080/api/method/a12345.

Cheers,
Andreas

**Comment by MRC-CBT** [comment]
Hi Andreas,
Thank you for answering so quickly, as you correctly guessed, I am using the webservices module. After starting from your example, which worked a-ok, and building up to mine, which was failing, it looks like my problem is due to the ID I am passing being a guid. The router doesn't seem to accept hyphens. Is this a known issue or am I using this incorrectly?
Many thanks,
Matt

**Comment by Kaliumhexacyanoferrat** [comment]
Hi Matt,

ah, I see. Yes, the handler will match alphanumeric characters only by default. You can add a custom pattern like this:

```csharp
[ResourceMethod("method/(?<id>[a-z0-9-]+)")] // or a pattern matching a GUID
public string Method(string id) => id;
```

I will clarify the documentation in this regard. sorry for the inconvenience.

**Comment by Kaliumhexacyanoferrat** [comment]
I guess, we figured out the issue, so I will close this one here. Feel free to re-open, if there are additional questions.
