### ISSUE TITLE
Variable pass to Scriban example. 

### ISSUE THREAD

**Issue by DraconInteractive** [Kaliumhexacyanoferrat/GenHTTP#178]
Hi! 

I am fairly inexperienced with web dev, so some concepts are passing me by. In particular, I have never used (or even heard of) Scriban before. 

I have a working version of the website, using a series of html pages loaded at start as such: 
```csharp
ModScriban.Page(Resource.FromAssembly(Path + ".html")).Title(Name);
```

I am now trying to change variables being passed through at runtime, which I assume is the purpose of the scriban example in the docs (which mentions a ShopModel and Basket variable). I have attempted to implement this in my own way, as so: 

```csharp
public class AIModel : PageModel
  {
      public string DOut { get; }
      public AIModel(IRequest request, IHandler handler, string dOutput) : base(request, handler)
      {
          DOut = dOutput;
      }
  }

//Example of my constructor: 
return ModScriban.Page(Resource.FromAssembly(Path + ".html"), (request, handler) => new AIModel(request, handler, "5"));
```

This is just a tester, meant to output the string "5" to the area specified on the site. 
Inside the html file being loaded, I have put two lines (I wasnt sure which variable would be referenced). 
`{{DOut}}
{{dOutput}}`

In the area of the page where these would show, I am seeing absolutely nothing however. Is my entire flow wrong, or have I just missed a step? 

PasteBins
[Website Constructor](https://pastebin.com/ST7t4Eer)
[Page Constructor](https://pastebin.com/Bj23gwyB)
[HTML](https://pastebin.com/ey2iuS4M)

**Comment by DraconInteractive** [comment]
Thank you so much for the quick answer! I am on Australia time (AWST), so I'm going to check this out in the morning. 
MVC was on my chart to look at after getting a website working, so I'll make that a priority :) 

Interestingly, I managed to get a somewhat working version by reading the .html with ReadAllText, and then passing that to the page using Resource.FromString. That was I was able to run a filter over the html text and parse in my own variables. 
E.g, in the html I could have <h3>[--subtitle--]</h3>, and in my code I had ReadAllText(path).Replace("[--subtitle--]", AI.Subtitle);

There are obvious problems with that solutions though, so im glad to have another path!

**Comment by Kaliumhexacyanoferrat** [comment]
Your approach is actually quite similar to the `Placeholders.Page()` handler which provides a very basic, reflection based string replacement mechanism that is used by the core server to render its pages without having dependencies on a templating engine. Nevertheless, you will soon reach some limits such as `foreach` and `if` constructs. 

I am currently working on [project templates](https://github.com/Kaliumhexacyanoferrat/GenHTTP.Templates) that can be used with `dotnet new` to make the initial project setup way easier.

**Comment by Kaliumhexacyanoferrat** [comment]
Just an additional note ... [AdminLTE](https://adminlte.io/themes/dev/AdminLTE/index3.html) is based on [Bootstrap](https://getbootstrap.com/docs/4.3/getting-started/introduction/) which allows you to use a lot of different controls out of the box (such as buttons, data grids, ...), so you do not need to waste your time on CSS.

**Comment by DraconInteractive** [comment]
I had a look at the .zip you provided, the entire process is immediately clearer :) I spent some time converting my system to that model, works perfectly! 

The project templates sound like a really good idea, i did most of my learning from the Demo template in the .Themes repo. 

Good to know its based on bootstrap! I have a small amount of experience with it, so thats a plus :)

Your help has been massively appreciated here :)

**Comment by DraconInteractive** [comment]
Hi again! Sorry to bother, but is there currently functionality for more nested options within the AdminLTE theme? 
Currently creating sub options in the form of 
```/subject/item (e.g, /models/model01)```, 
but I'm trying to figure out if its possible to go
```/subject/sub-subject/item```. 

Any help appreciated!

**Comment by Kaliumhexacyanoferrat** [comment]
Currently only two levels of depth are supported by the theme. AdminLTE itself does support this option, so it surely can be added. Feel free to create a change request in the `Themes` repository, so I can have a look some time soon.

**Comment by DraconInteractive** [comment]
Thanks for the info! May do so when I get the chance, but its not high priority, and you have a lot on your hands :)

**Comment by DraconInteractive** [comment]
Is there a known issue around the page assigned as Index returning Internal Error 500? 
I had a few weird encounters with it loading random other index pages, like the Index of the AIController, but now its just not loading at all. 

Here is my setup function: 
```csharp
private static void Setup()
        {
            var resources = new string[]
            {
                "avatar.png",
                "logo.png"
            };

            var main = Layout.Create()
                .Add("models", Controller.From<AIController>())
                .Add("games", Controller.From<GameController>())
                .Add("systems", Controller.From<SystemController>())
                .Add("reports", Controller.From<ReportController>())
                .Add("user", ModScriban.Page(Resource.FromAssembly("user.html")).Title("Internal Systems"))
                .Index(ModScriban.Page(Resource.FromAssembly("index.html")).Title("Home"));


            foreach (var resource in resources)
            {
                main.Add(resource, Download.From(Resource.FromAssembly(resource)));
            }

            var menu = Menu.Empty()
                    .Add("{website}", "Home")
                    .Add("/games/", "Games", GameController.Links())
                    .Add("/models/", "AI Models", AIController.Links())
                    .Add("/systems/", "Systems", SystemController.Links());

            var website = Website.Create()
                .Theme(GetAdminLTE())
                .Menu(menu)
                .Content(main);

            Host.Create()
                .Defaults()
                .Console()
                .Handler(website)
                .Run();
        }
```

The site runs perfectly aside from the Index. I have tried changing index.html location, no luck.
index.html is very simple, and did work at one stage (a while ago). Here it is: 

```html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<body>
    <h4>Index!</h4>
</body>
</html>
```

Thanks again for any help :)
I have made my repository public, if you need you can view at [The github page](https://github.com/DraconInteractive/GenHTTP_WebServer )

**Comment by DraconInteractive** [comment]
Fixed by making index.html "Content" instead of "Embedded Resource" and then using Resource.LoadFile. Still not sure why it didnt like it as an embedded resource (all my other files are embedded)

**Comment by Kaliumhexacyanoferrat** [comment]
The `Resource.FromAssembly("index.html")` looks for any file reference within your project DLL that ends with the string `index.html`. Because assembly resources do not have a concept of "a folder", the first file found by the server is `system_index.html` which ends with `index.html`. This is actually a comfort feature which allows you not to fully qualify every file name (which would be `GenHTTP_WebServer.index.html` or `GenHTTP_WebServer.Pages.ai_index.html`.

Nevertheless - In this case I would also expect the handler to lookup a file with just the name `index.html` (which translates to `EndsWith(".index.html")`. I will create an improvement for this, thanks! Let's see whether there are acceptance tests breaking with this constraint.

You can debug such issues by activating the development mode:

```csharp
Host.Create()
    .Defaults()
    .Console()
    .Handler(website)
#if DEBUG
    .Development()
#endif
    .Run();
```

Besides activating stack traces this changes a few things that improve the development flow of a website (such as serving JavaScript files separately instead of bundling them).

![image](https://user-images.githubusercontent.com/4992119/105490663-6481db80-5cb5-11eb-8d45-6a5f3bda19e5.png)

**Comment by DraconInteractive** [comment]
Makes sense! Glad I could help highlight an area for future work :)

**Comment by Kaliumhexacyanoferrat** [comment]
So if there are no more open questions from your side, I will close this issue. Feel free to open a new one as needed :)
