### ISSUE TITLE
The type arguments for method 'ModScriban.Page<T>(IBuilder<IResource>, ModelProvider<T>)' cannot be inferred from the usage

### ISSUE THREAD

**Issue by satpal123** [Kaliumhexacyanoferrat/GenHTTP#246]
Getting the following error when changed from .Net 5 to 6 using VS 2022

![image](https://user-images.githubusercontent.com/710270/141731194-03de2e4b-a3b9-41a3-9176-65dcc83bbf47.png)

**Comment by Kaliumhexacyanoferrat** [comment]
This call has changed to be `async` in release 6. I will have a look whether I can make this change more transparent. The following line will compile:

```
return ModScriban.Page<ViewModel<T>>(Resource.FromAssembly(file), (r, h) => new(new ViewModel<T>(r, h, data)))
```

The templates have been updated accordingly.

**Comment by satpal123** [comment]
Thanks now its compling. :)
