### ISSUE TITLE
Add support for protobuf

### ISSUE THREAD

**Issue by Kaliumhexacyanoferrat** [Kaliumhexacyanoferrat/GenHTTP#293]
As a developer of a web service (or controller), I would like to use [Protocol Buffers](https://developers.google.com/protocol-buffers) to transmit data more efficiently to my clients. 

**Example**

```csharp
using GenHTTP.Modules.Protobuf;

var serialization = Serialization.Default() // or .Empty()
                                 .AddProtobuf();

var service = ServiceResource.From<MyClass>()
                             .Formats(serialization);
```

**Acceptance criteria**

- There is a new class implementing `ISerializationFormat`
- The functionality is implemented in a new module
- `ContentType` has been extended with `application/protobuf` content type
- There are acceptance tests to ensure functionality

**Comment by wcontayon** [comment]
It's a interesting issue. @Kaliumhexacyanoferrat  can I try a PR ?

**Comment by Kaliumhexacyanoferrat** [comment]
@wcontayon : sure :)
