### ISSUE TITLE
is it possible to run with xamarin forms

### ISSUE THREAD

**Issue by ygl-rg** [Kaliumhexacyanoferrat/GenHTTP#294]
Hi All

   Recently I want to run an embedded server on my mobile app in order to host a vue.js app. Is it possible to run genhttp on mobile device?

Regards

gelin yan

**Comment by Kaliumhexacyanoferrat** [comment]
As Xamarin runs with .NET 6 and you are allowed to host a webserver on Android, this should work. Did you try starting a host instance? I will have a look next week maybe.

**Comment by Kaliumhexacyanoferrat** [comment]
Xamarin only supports class libraries of target framework `netstandard2.0`. The support for this was removed from GenHTTP as it had some serious downsides. Nevertheless, as MAUI can target `net6.0`, you can host a server instance there:

![image](https://user-images.githubusercontent.com/4992119/207845532-4262a01e-ef2d-4098-9af7-342f63088247.png)
