### ISSUE TITLE
Failed to route empty parameters

### ISSUE THREAD

**Issue by Fiahblade** [Kaliumhexacyanoferrat/GenHTTP#299]
Empty parameters aren't routed properly, expected it to reach the methode. Instead the server returned 500.

**Examples**

```
 GET /test?var1=
 GET /test?var1=example&var2=

// 500 Internal Server Error
// The server failed to handle this request.
```

I've tried allowing null or setting default values, all without luck.
```csharp
    [ResourceMethod(RequestMethod.GET, "test")]
    public bool MyMethode(string? var1, string? var2)
    
    [ResourceMethod(RequestMethod.GET, "test")]
    public bool MyMethode(string var1 = "", string var2 = "")
```

**Additional Information**

- It doesn't matter how many parameters you have, if one of them is empty then the server returns 500
- From what I can tell this only happens with strings, non null-able types return to their default values.

**Comment by Fiahblade** [comment]
@Kaliumhexacyanoferrat Hi, when you find the time, could you check out my proposed solution?
I'll create a pr if this seems acceptable for you.

**Comment by Kaliumhexacyanoferrat** [comment]
@Fiahblade: Makes sense to me, yet I have the feeling that there are unit tests for the scenario described in your bug report.

Feel free to create a PR for your change, an additional test for this branch would be nice.

Thanks for your contribution and sorry for the late response - our new born takes all our time currently 😉

**Comment by Fiahblade** [comment]
No worries and congrats are in order!
I'll see if I can push this forward in the coming days.

**Comment by Kaliumhexacyanoferrat** [comment]
@Fiahblade: fixed in `v6.3.5` and `master`, thank you very much!

**Comment by Kaliumhexacyanoferrat** [comment]
Published your changes to the website as well.

**Comment by Fiahblade** [comment]
You're most welcome, glad to give something back.
