### ISSUE TITLE
Include Authorization header in permissive CORS policy

### ISSUE THREAD

**Issue by Kaliumhexacyanoferrat** [Kaliumhexacyanoferrat/GenHTTP#302]
As a developer of a web application, I would like the `Authorization` header to be allowed in `CorsPolicy.Permissive()`, so that I do not need to care about this detail.

**Acceptance criteria**

- When `CorsPolicy.Permissive()` is used, the server returns the `Authorization` header field in `Access-Control-Allow-Headers`
- The implementation of the .NET Web API has been checked for further cases
- There is an acceptance test for this behavior

**Comment by wcontayon** [comment]
Hi @Kaliumhexacyanoferrat 
Interesting issue and project, can I try a PR ?

**Comment by Kaliumhexacyanoferrat** [comment]
@wcontayon absolutely - contributions are very welcome 👍
