### ISSUE TITLE
Reverse proxy issues

### ISSUE THREAD

**Issue by Matasx** [Kaliumhexacyanoferrat/GenHTTP#333]
1. connectTimeout is not respected (unused in the class ctor)
https://github.com/Kaliumhexacyanoferrat/GenHTTP/blob/1360304dbdd6c68ae8cf27ae2f93bd8345797958/Modules/ReverseProxy/Provider/ReverseProxyProvider.cs#L54-L69

3. Reserved headers are case sensitive, should be case insensitive. I.e. when using `content-type` instead of hardcoded `Content-Type`, the server will return HTTP 500. 
https://github.com/Kaliumhexacyanoferrat/GenHTTP/blob/1360304dbdd6c68ae8cf27ae2f93bd8345797958/Modules/ReverseProxy/Provider/ReverseProxyProvider.cs#L22-L40

(Sorry I did not provided any repro steps, but I think it is self explanatory).

**Comment by Kaliumhexacyanoferrat** [comment]
@Matasx : Thank you very much, both issues have been fixed on `master`.
