### ISSUE TITLE
Routing mechanism in SPAs has "unexpected" behaviour.

### ISSUE THREAD

**Issue by ImOliwer** [Kaliumhexacyanoferrat/GenHTTP#340]
When the SPA has a routing mechanism of whatever kind, it displays a 'not found' page from GenHTTP, and not the expected page.

**Example**
`/` - shows the expected page.
`/routed-page` - displays a `not found` page by GenHTTP.

```csharp
Host.Create()
  .Defaults()
  .Port(Shared.ServerPortWebApp)
  .Handler(SinglePageApplication.From("web-app".FromWorkingDir().AsResourceTree()))
  .Start();
```

**Additional Information**

- I am running v6.4.0.
- The resource directory passed to the SPA is a built React app.

**Comment by ImOliwer** [comment]
That would explain it. I tried looking through the existing issues - closed and open - but could not for the life of me find one related to this. Apparently there were and I wasn't looking close enough. Thank you for your response regarding this, Kalium.

I'm not sure whether you'd like me to close this or not so I'll leave that up to you when you see this.

**Comment by Kaliumhexacyanoferrat** [comment]
No worries - if this is a common scenario the framework should support this use case and it should be documented on the website as well. Just created #341 and will inform you as soon as this is fixed.

**Comment by ImOliwer** [comment]
Yeah I thought it would've been on the website but I went around the categories of content providers but I had no luck finding information regarding SPA with features such as routing. I'll be awaiting your response whilst I watch over #341.

**Comment by Kaliumhexacyanoferrat** [comment]
Will be solved in GenHTTP 7, with the documentation [here](https://github.com/Kaliumhexacyanoferrat/GenHTTP.Website/blob/master/Project/Pages/Documentation/Content/SinglePageApplications.md). Thank you for your report!
