### ISSUE TITLE
Question: How to stream output?

### ISSUE THREAD

**Issue by varon** [Kaliumhexacyanoferrat/GenHTTP#371]
Hi,

I'd like to be able to stream content to the body of a request - imagine a long-running request body with a counter that outputs:
```
1
2
3
4
```
once per second, for up to N seconds.

I've spent 2-3 hours trying to figure out how to get a response stream and write to it, but it seems like some buffering and other weirdness is in the way. Any ideas on how to achieve this?

Thanks for making this nice and simple server otherwise.

**Comment by Kaliumhexacyanoferrat** [comment]
Hi varon

Sounds like https://github.com/Kaliumhexacyanoferrat/GenHTTP/discussions/309 could solve your issue?

Cheers
Andreas

**Comment by varon** [comment]
Thank you - that will almost certainly work. It would be great if this were exposed in the API as you suggested.

**Comment by Kaliumhexacyanoferrat** [comment]
Created #373 for this.

**Comment by Fiahblade** [comment]
Is the discussed code is there a way to 'execute code' when the stream closes/terminates?

**Comment by Kaliumhexacyanoferrat** [comment]
So when the client disconnects and the server is no longer able to push data? Currently not, but an optional handler could be added for this case.

**Comment by Kaliumhexacyanoferrat** [comment]
Closing this in favor of #373
