### ISSUE TITLE
How to receive POST data for webservice?

### ISSUE THREAD

**Issue by DraconInteractive** [Kaliumhexacyanoferrat/GenHTTP#387]
Hi, 
I'm trying to retrieve data from the body of a POST request.

Im defining the resource like this: 
```cs
[ResourceMethod(RequestMethod.POST)]
public string UpdateData(string id)
{ ... }
```

I initially tried doing a post request like this: `POST http://localhost:8080/data`, and attaching a body like so: 
```json
{
    "id": "testID"
}
```

But querying id in the UpdateData method returned empty. 

I can make this work if I were to query the uri like so: `POST http://localhost:8080/data?id=testID`
However I'd like to make it so that I can actually put json data into here, which means attaching the data to the body like I would normally do with a POST request. 

Can you let me know what I'm doing wrong? 
Much appreciated :)

**Comment by Kaliumhexacyanoferrat** [comment]
You will to use need an additional type for this:

```
[ResourceMethod(RequestMethod.POST)]
public string UpdateData(UpdateDataRequest request)
{ ... }

public record UpdateDataRequest(string ID);
```

Which has the advantage that you can add additional properties later on 😉

**Comment by DraconInteractive** [comment]
Ah that explains the template, thanks! 

To expand on this, what approach would I take if I wanted to supply id as a parameter but also access the body? 

Something like this? 
```
[ResourceMethod(RequestMethod.POST)]
public string UpdateData(int id, UpdateDataRequest request)
{ ... }

public record UpdateDataRequest(string someData);
```

**Comment by Kaliumhexacyanoferrat** [comment]
The following works for me:

```csharp
using GenHTTP.Api.Protocol;
using GenHTTP.Engine;
using GenHTTP.Modules.Layouting;
using GenHTTP.Modules.Security;
using GenHTTP.Modules.Webservices;

namespace PostTest
{

    internal class Program
    {

        static void Main(string[] args)
        {
            var service = Layout.Create()
                        .AddService<TestService>("service")
                        .Add(CorsPolicy.Permissive());

            Host.Create()
                .Handler(service)
                .Run();
        }

    }

    public class TestService
    {

        [ResourceMethod(RequestMethod.POST, "data/test")]
        public string TestPost(TestPostRequest request)
        {
            return $"Request received: {request}";
        }

    }

    public record class TestPostRequest(string UserID, string Content);

}
```

invoked like this:

![image](https://github.com/Kaliumhexacyanoferrat/GenHTTP/assets/4992119/10473af3-db19-44fb-851c-659455adba99)

If there is a `HTTP 500` you will see an exception in the logs if you enable `.Development()` mode on the server host. That should help to pin down your issue.

**Comment by DraconInteractive** [comment]
After testing the above, with both .Console and .Development I still wasnt getting any useful errors (.Console just added that the request had been received with a 500 error). 

However, I had been using Unity thus far, so i did a quick install of postman and it started working, so looks like Unity is deforming my request in some way. Probably encoding or something similar. 

I appreciate the time you took to go through this with me :)

**Comment by DraconInteractive** [comment]
Can confirm, Unity was encoding the data in the backend, once I did it manually issue was all fixed. 

Thanks again, love the package!

**Comment by Kaliumhexacyanoferrat** [comment]
Glad it works. Would be interesting for me what caused the `HTTP 500`. If you have some additional insights, feel free to come back on me again.

**Comment by DraconInteractive** [comment]
Absolutely :)

So Unity was automatically URL Encoding the body for its default UnityWebRequest.Post. 
In order to fix it, I created a manual UnityWebRequest and created the upload handler like this: 
```
    request.uploadHandler = new UploadHandlerRaw(System.Text.Encoding.UTF8.GetBytes(body));
    request.downloadHandler = new DownloadHandlerBuffer();
    request.method = UnityWebRequest.kHttpVerbPOST;
```

The URL Encoding would have deformed the JSON packet (e.g all the " become %22)

Regarding a server side fix, I suppose you could detect and convert it back, or you could return a message in the .Development return (e.g "Invalid json packet. Ensure formatting and encoding are correct."). 
Just ideas, my exposure to backend dev is minimal to say the least :)

**Comment by Kaliumhexacyanoferrat** [comment]
To be improved in #393
