### ISSUE TITLE
The application called an interface that was marshalled for a different thread

### ISSUE THREAD

**Issue by leonardoburchi** [Kaliumhexacyanoferrat/GenHTTP#397]
Hello,
I embedded GenHTTP into a WinUI 3 application and I'm trying to develop a set of web services to interact with the desktop application from remote. The application will run only on Windows and it is composed by a set of desktop windows and it is a timer that can be shown on a monitor and it could be controlled remotely or directly from the local pc.
So I created a resource method for GenHTTP to start the timer 

```
public class ClockManagerResource
{
    [ResourceMethod("startshootclock")]
    public void StartShootClock()
    {
        Match m = (App.Current as App).match;
        m.ShootClock.Start();
    }

    [ResourceMethod("startperiodclock")]
    public void StartPeriodClock()
    {
        Match m = (App.Current as App).match;
        m.PeriodClock.Start();
    }
}
```

And it works perfectly starting the timer. Then I added an event on Timer class like you see below:

```
protected virtual void OnTimerStarted(TimerChangedArgs e)
{
    EventHandler<TimerChangedArgs> handler = TimerStarted;
    if (handler != null)
    {
        handler(this, e);
    }
}

public event EventHandler<TimerChangedArgs> TimerStarted;
```

On the xaml.cs of the window I subscribed the event with the intent of changing the status of the toggle button that start/stop the timer on the desktop application:

```
private void PeriodClock_TimerStarted(object sender, BasketballGameManager.Base.TimerChangedArgs e)
{
    PeriodClockStartStop.IsChecked = true;
}
```

The event is correcly triggered but I have the exception "The application called an interface that was marshalled for a different thread"
when I try to change the status of the button.

Could you please help me to understand how can I solve this issue?

Thank you in advance for your help!!

**Comment by Kaliumhexacyanoferrat** [comment]
Timers (as well as GenHTTP handlers) are invoked on worker threads, not the UI thread. Only the UI thread is allowed to change your UI. To run on the UI thread, you can use:

```
 DispatcherQueue.TryEnqueue(() => { PeriodClockStartStop.IsChecked = true; });
```

See this [SO question](https://stackoverflow.com/questions/73466296/a-winui-3-question-about-accessing-the-ui-thread-from-another-thread).

**Comment by leonardoburchi** [comment]
Thanks a lot for your answer. It works perfectly!

Thanks again!
