### ISSUE TITLE
wpf 

### ISSUE THREAD

**Issue by Prachi-Infosoft** [Kaliumhexacyanoferrat/GenHTTP#404]
> May I get a working example of embedding in wpf application..

**Comment by Kaliumhexacyanoferrat** [comment]
The [server setup](https://genhttp.org/documentation/server/) guide works for any framework that runs on .NET >= 6.

Nevertheless you will find a minimal sample attached here (after starting the server you will be able to call http://localhost:8080 in your browser).

[WpfSample.zip](https://github.com/Kaliumhexacyanoferrat/GenHTTP/files/12725886/WpfSample.zip)
