### ISSUE TITLE
Extract client IP Address

### ISSUE THREAD

**Issue by DraconInteractive** [Kaliumhexacyanoferrat/GenHTTP#406]
Heyyo, me again :) 

I've implemented a rest api using a handler instead of the full webservice integration. In the handler, I have the HandleAsync method, which takes an IRequest input. 

The request object has a client.IPAddress variable, but I am only ever getting 0.0.0.1. Given this is in the reserved range, and I also get it for requests from different networks, I assume this is just a default value. 

Do you know how I can access that address properly then?

**Comment by Kaliumhexacyanoferrat** [comment]
Hi - sorry for the late response. The IP address is either read from the TCP connection or - if there is a proxy in front of your webserver - read from the `X-Forwarded-For` header. Before looking into this, do you have a proxy in front of your service and which one is it? Do you use Docker or something similar for your setup?

**Comment by Kaliumhexacyanoferrat** [comment]
Hey @DraconInteractive - any news on this? Otherwise I would close this issue for now.

**Comment by DraconInteractive** [comment]
Apologies, a dozen things evolved and I kept meaning to update as my approach changes but it happened too many times. I cant really give a satisfying conclusion other than 'enough things changed that this was no longer needed, and i didnt pursue it further'

I will get back to you if I explore it more in the future!

**Comment by Kaliumhexacyanoferrat** [comment]
No worries - created #437 for this if it happens again so the issue can be debugged more easily.
