### ISSUE TITLE
Multiple errors when trying to access site as https

### ISSUE THREAD

**Issue by LasseBuchAspIT** [Kaliumhexacyanoferrat/GenHTTP#407]
the console throws multiple errors and doesnt return a site when accessed via https://localhost instead of http://localhost...
is https not supported?
![image](https://github.com/Kaliumhexacyanoferrat/GenHTTP/assets/97156204/d93629f0-fdaf-4faa-ba0f-1df667352d33)
d?

**Comment by Kaliumhexacyanoferrat** [comment]
To configure and enable SSL, see https://genhttp.org/documentation/server/security.

While GenHTTP can be configured for SSL, it is generally recommended to use a reverse proxy in front of your application which handles encryption. There is the [GenHTTP.Gateway](https://hub.docker.com/r/genhttp/gateway) for this purpose, but you may want to have a look at nginx, apache or traefik as well.
