### ISSUE TITLE
set response type

### ISSUE THREAD

**Issue by Prachi-Infosoft** [Kaliumhexacyanoferrat/GenHTTP#408]
I want to use GENHTTP as web API. 

```
            var handler = GenHTTP.Modules.Functional.Inline.Create()
                    .Get("getcompany", (string dbname) =>
                    {
                        var response = new {data:"123"}

                    });
```
How to serialize as json OR XML?

**Comment by Kaliumhexacyanoferrat** [comment]
Just return the data object:

```csharp
var handler = Inline.Create()
                    .Get("getcompany", (string dbname) => new { data = "123"});
```

Invoking this via http://localhost:8080/getcompany/ will return the JSON object as expected.

![image](https://github.com/Kaliumhexacyanoferrat/GenHTTP/assets/4992119/c91bfa97-1f48-4ede-bade-0978e580af6f)

If you would like it to serialize as XML, set the `Accept: text/xml` header in your client.

For advanced serialization features, see [the documentation](https://genhttp.org/documentation/content/conversion).

**Comment by Kaliumhexacyanoferrat** [comment]
I will close this issue for now. If you have further questions on this topic, please feel free to re-open.
