### ISSUE TITLE
Server Not Stopping

### ISSUE THREAD

**Issue by GundlackFlorian** [Kaliumhexacyanoferrat/GenHTTP#410]
Hello,

I'm trying the library, and i noticed with this very simple code even when i asked the server to stop it is still launched ( i still can load the page and i'm getting OnRequestHandled Events).

What am i doing wrong ?

```
public class Companion : IServerCompanion
{
    public void OnRequestHandled( IRequest request, IResponse response )
    {
        Trace.WriteLine( $"OnRequestHandled: {request.Client}" );
    }

    public void OnServerError( ServerErrorScope scope, Exception error )
    {
        Trace.WriteLine( "OnServerError" );
    }
}

public class HttpServer
{
    private IServerHost ServerHost { get; set; }
    private Companion Companion { get; } = new();

    public HttpServer()
    {
        var content = Content.From( Resource.FromString( "Hello World!" ) );

        ServerHost = Host.Create()
            .Port( 8081 )
            .Defaults()
            .Companion( Companion )
            .Handler( content );
    }

    public void Start()
    {
        ServerHost.Start();
    }

    public void Stop()
    {
        ServerHost.Stop();
    }
}
``` 

The Start And Stop are called in an visual app with a button.
Version is from nugget: 7.0.0.

Thanks in advance for your answer.

**Comment by Kaliumhexacyanoferrat** [comment]
Hi Florian,

thank for reporting this issue. This should definitely not be the case. I will analyze this beginning of next week and provide a fix if I can reproduce this behavior.

**Comment by GundlackFlorian** [comment]
Thanks !
I just noticed that if no request is done for some time (a few seconds) then the server seems to stop.
So for example if you keep reloading the page it nerver stops.

In my case i have an app that is doing continuous request per seconds so the server never stops.

**Comment by Kaliumhexacyanoferrat** [comment]
Ah, so the worker thread that (asynchronously) handles the connection is not forcibly shut down by the host. I probably need to find a concept that allows to gracefully finish requests while still enforcing some kind of timeout (e.g. `Stop(Duration timeout)`) - in a similar way Apache implements this ... a fix will probably not be available beginning of next week then I guess 😁

**Comment by Kaliumhexacyanoferrat** [comment]
Added a simple way that prevents the `ClientHandler` from processing new requests after the server has been stopped. The handler will still keep processing the current request, which requires more thought, but for the moment this should solve your issue.
