### ISSUE TITLE
Localhost (Windows) issue when using PUT

### ISSUE THREAD

**Issue by Matasx** [Kaliumhexacyanoferrat/GenHTTP#485]
Hi, long time no see. 😃 

When I'm using GenHTTP just over localhost. I.e. I have the server and client on the same machine and when I use PUT method (see the example), I would expect the server to handle the request. Instead it fails with `HttpIOException: The response ended prematurely.`
Interestingly enough, when I try to intercept the request on client side to see what is going wrong, then the request passes through (you can uncomment the line with logging handler to see it pass). 
I've encountered this issue in the past, now I was able to isolate it to a single example, but I don't know what's causing it or how to troubleshoot it.

Any help would be much appreciated!

**Example**

```csharp
using GenHTTP.Api.Protocol;
using GenHTTP.Modules.Functional;
using GenHTTP.Modules.Practices;
using System.Net.Http.Json;
using System.Text;

namespace ReproSteps
{
    internal class Program
    {
        static async Task Main(string[] args)
        {
            ushort port = 82;

            GenHTTP.Engine.Host
                .Create()
                .Handler(Inline.Create().Put("/test", (IRequest x) => Console.WriteLine($"Received: {new StreamReader(x.Content).ReadToEnd()}")))
                .Defaults()
                .Port(port)
                .Console()
                .Development()
                .Start()
                ;

            using var client = new HttpClient(
                //Uncomment this line:
                //new LoggingHandler(new HttpClientHandler())
                )
            {
                BaseAddress = new Uri($"http://localhost:{port}/")
            };

            var response = await client.PutAsJsonAsync("test", new Model("val"));
            response.EnsureSuccessStatusCode();

            while (true)
            {
                await Task.Delay(1000);
            }
        }

        private record Model(string Value);

        private class LoggingHandler(HttpMessageHandler innerHandler) : DelegatingHandler(innerHandler)
        {
            protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            {
                if (request.Method != HttpMethod.Post && request.Method != HttpMethod.Put)
                    return await base.SendAsync(request, cancellationToken);

                StringBuilder logBuilder = new();
                logBuilder.AppendLine("Request:");
                logBuilder.AppendLine(request.ToString());
                if (request.Content != null)
                {
                    logBuilder.AppendLine(await request.Content.ReadAsStringAsync(cancellationToken));
                }
                logBuilder.AppendLine();

                var response = await base.SendAsync(request, cancellationToken);

                logBuilder.AppendLine("Response:");
                logBuilder.AppendLine(response.ToString());
                if (response.Content != null)
                {
                    logBuilder.AppendLine(await response.Content.ReadAsStringAsync(cancellationToken));
                }
                logBuilder.AppendLine();

                Console.WriteLine(logBuilder.ToString());

                return response;
            }
        }
    }
}

```

**Additional Information**

- Note that it does not matter if Inline or webservice is used.
- This snippet passes if server and client are running on different machines.
- Using latest version with .Net 8 (but I was alble to reproduce with older version and on .Net 6)
- I'm using Windows 11 if that might be also a concern.
- I was able to also reproduce when running as a Docker with Linux base .net image, but hosted on Windows

**Comment by Kaliumhexacyanoferrat** [comment]
Thanks for the detailed report - I will have a look beginning of next week.

**Comment by Matasx** [comment]
I spend few more minutes looking into to. I was not able to find the root couse, but I made some progress. Probably the issue would be somewhere on the client side and related to JsonContent. (Although it is possible the client side issue only manifests with the way how GenHTTP is handling requests, but I was not able to confirm this.)

I.e. this works:
```C#
var response = await client.PutAsync("test", new StringContent("val"));
```
This does not work:
```C#
JsonContent content = JsonContent.Create(new Model("val"));
var response = await client.PutAsync("test", content);
```
This works:
```C#
JsonContent content = JsonContent.Create(new Model("val"));
var str = await content.ReadAsStringAsync();
var response = await client.PutAsync("test", content);
```

The `content.ReadAsStringAsync` causes it to serialize the model into memory and store inside buffered stream which is then transffered fine. But without the "pre-evaluation" it does not work. 

Next steps would be probably to intercept on lower level with e.g. wireshark and observe differences of the http request itself.

**Comment by Kaliumhexacyanoferrat** [comment]
Thanks again for the details - was able to reproduce the issue right away. The request failed because the client sent the request body as `Transfer-Encoding: chunked` which was not implemented by the server engine yet. 

Support for chunked request bodies has been added in version `8.3.2`, so this should work now.

**Comment by Matasx** [comment]
Wow this is great. Thank you!
