### ISSUE TITLE
Add support for Websockets (RFC 6455)

### ISSUE THREAD

**Issue by Kaliumhexacyanoferrat** [Kaliumhexacyanoferrat/GenHTTP#82]
As a developer of a reactive, rich client-application, I would like to use websocket connections to the webserver, so that I can easily push content from the server to the clients.

**Example**

Very vague - clarity comes with implementation.

```csharp
class IWebsocketHandler 
{
    void Initialize(Connection connection);
    void HandleFrame(Frame frame);
}

var socket = Websocket.Create<MyHandler>();
```

**Acceptance criteria**

- The `Websocket` handler is a regular `IHandler` that can be added where required
- There is a separate `GenHTTP.Modules.Websocket` module, with a minimal hook into the server core to gain control over the socket

**Comment by ToshiroZ** [comment]
This would be quite helpful to have

**Comment by Kaliumhexacyanoferrat** [comment]
Websockets, along with form-based authentication, are the next topics on the agenda.

Due to my parental leave in summer, there will be few changes from my side in the next months. Pull requests or preparatory changes are of course always welcome.

**Comment by ToshiroZ** [comment]
Would it also be possible to render a page without any theming? Basically
increment some data then view page

**Comment by Kaliumhexacyanoferrat** [comment]
If you would like to use the `Website` module, you will need a theme - an empty theme should not be much effort. If you do not need the features provided by the `Website`, you can just render a `Page` in the default server theme:

```
var page = Page.From("My Content") // or ModScriban.Page() or ModRazor.Page() or Placeholders.Page()
               .Title("My Title")
               .Description("My description");

var layout = Layout.Create()
                   .Add("page", page);

Host.Create()
    .Handler(layout)
    .Defaults()
    .Development()
    .Console()
    .Run();
```

`Razor` and `Scriban` allow you to render a model into a template (e.g. read from the file system).

**Comment by Kaliumhexacyanoferrat** [comment]
Or, if you are fine with plain text, even easier:

```
var handler = Inline.Create()
                    .Get("/page", () => "Hello World!");

Host.Create()
    .Handler(handler)
    .Run();
```

**Comment by yuexueyang** [comment]
How about the websocket module, is it ready for use?

**Comment by Fiahblade** [comment]
Are there still plans to include this feature?

**Comment by Kaliumhexacyanoferrat** [comment]
Yes, web sockets are one of the more important features but as the protocol is rather complex that will take some effort to be implemented.

**Comment by Kaliumhexacyanoferrat** [comment]
Notes: Probably do not implement this ourselves but reuse an existing library and just pass the server socket together with some glue code for upgrading the connection. Need to check whether this is possible in one of the suspects.

**Comment by Kaliumhexacyanoferrat** [comment]
Will be available with GenHTTP version 9 in November.

**Comment by jakerdy** [comment]
Is it possible to serve both http and websockets in one app? It seems that I can't just add WebSocket.Create() value to Layout...
