### ISSUE TITLE
Allows description of pages to be specified

### ISSUE THREAD

**Issue by Kaliumhexacyanoferrat** [Kaliumhexacyanoferrat/GenHTTP#94]
As the developer of a public website, I would like to set the description of rendered pages so that my SEO rank improves.

**Example**

```csharp
var page = ModScriban.Page()
                     .Title("My Title")
                     .Description("My Description");
```

**Acceptance criteria**

- The page model has been extended by an additional, optional property to describe a page
- The property is respected in all places where title is respected as well
- The change has been released and all [themes](https://github.com/Kaliumhexacyanoferrat/GenHTTP.Themes) have been updated

**Comment by ondator** [comment]
Seems like done. @Kaliumhexacyanoferrat Please [take a look](https://github.com/Kaliumhexacyanoferrat/GenHTTP/pull/100)

**Comment by Kaliumhexacyanoferrat** [comment]
Thanks @ondator! I made the description optional (`string?`) so the themes can decide whether they need to generate the meta tag or not. After the MVC branch has been merged I will release version 4 so the themes can be updated.
