### ISSUE TITLE
Add module to render pages from Markdown

### ISSUE THREAD

**Issue by Kaliumhexacyanoferrat** [Kaliumhexacyanoferrat/GenHTTP#96]
As the developer of a website, I would like to describe my pages in Markdown, so that I can focus on content and be more productive.

**Example**

```csharp
var layout = Layout.Create()
                   .Add("legal", ModMarkdown.Page(Data.FromFile("legal.md"));
```

**Acceptance criteria**

- The functionality is implemented in a new module
- The API aligns with the other rendering engines

**Comment by ondator** [comment]
@Kaliumhexacyanoferrat Hi, Andreas! I add this functionality in [this PR](https://github.com/Kaliumhexacyanoferrat/GenHTTP/pull/99). Please take a look

**Comment by Kaliumhexacyanoferrat** [comment]
@ondator: Very nice, thanks!
